# Source: https://github.com/grafana/agent/issues/3282
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-eventhandler
  namespace: kube-prometheus-stack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
 name: node-exporter
 namespace: kube-prometheus-stack
 labels:
   agent: grafana-agent-integrations
spec:
  config:
    cache_path: /etc/eventhandler/eventhandler.cache
    logs_instance: kube-prometheus-stack/primary
  name: eventhandler
  type:
    unique: true
  volumeMounts:
  - mountPath: /etc/eventhandler
    name: agent-eventhandler
  volumes:
  - name: agent-eventhandler
    persistentVolumeClaim:
      claimName: agent-eventhandler
#  name: node_exporter
#  type:
#    allNodes: true
#    unique: true
#  config:
#    autoscrape:
#      enable: true
#      logs_instance: primary #default
#    rootfs_path: /default/node_exporter/rootfs
#    sysfs_path: /default/node_exporter/sys
#    procfs_path: /default/node_exporter/proc
#  volumeMounts:
#    - mountPath: /default/node_exporter/proc
#      name: proc
#    - mountPath: /default/node_exporter/sys
#      name: sys
#    - mountPath: /default/node_exporter/rootfs
#      name: root
#  volumes:
#    - name: proc
#      hostPath:
#        path: /proc
#    - name: sys
#      hostPath:
#        path: /sys
#    - name: root
#      hostPath:
#        path: /root