config:
  trusted_root_ca: |
${TRUSTED_ROOT_CA}
  clusters:
    - name: demo
      # issuer: https://dex.${KIND_IP}.nip.io:32000
      issuer: https://oidc:5557/dex
      client_id: kubernetes
      client_secret: SuperSecretSecret
      redirect_uri: http://dex-k8s-authenticator.127.0.0.1.nip.io/callback
      # redirect_uri: http://localhost:28000
      # k8s_master_uri: https://${KIND_IP}:8443
      k8s_ca_pem: |
${K8S_CA_PEM}

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"

  hosts:
    - host: dex-k8s-authenticator.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
