apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-app
  namespace: default
spec:
  dnsNames:
    - yourdomain.com
  secretName: certmanager-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer